### ISSUE TITLE
make vm/switch failing on bootctl update

### ISSUE THREAD

**Issue by ihgann** [mitchellh/nixos-config#17]
Hi @mitchellh, thank you so much for this repository. I realize you aren't a personal support line so no worries/rush/expectations are made when raising this issue.

I recently tried this with an Intel-based MacOS machine and VMware Fusion 12.

I followed the same VM settings. NixOS is version `21.11`.

I commented out `vm/secret`, but other than that, the settings are the same. When running `make vm/bootstrap`, I receive the following error:

```
NIXUSER=root /Library/Developer/CommandLineTools/usr/bin/make vm/switch
ssh -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p22 root@192.168.189.132 " \
                sudo NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 nixos-rebuild switch --flake \"/nix-config#vm-intel\" \
        "
Warning: Permanently added '192.168.189.132' (ED25519) to the list of known hosts.
Password:
building the system configuration...
Skipping "/boot/EFI/systemd/systemd-bootx64.efi", since a newer boot loader version exists already.
Skipping "/boot/EFI/BOOT/BOOTX64.EFI", since a newer boot loader version exists already.
updating systemd-boot from (249.7) to (249.5)
Traceback (most recent call last):
  File "/nix/store/jjmymx70npfmdl6fhjb71py9fhj9yrk3-systemd-boot", line 314, in <module>
    main()
  File "/nix/store/jjmymx70npfmdl6fhjb71py9fhj9yrk3-systemd-boot", line 267, in main
    subprocess.check_call(["/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/bin/bootctl", "--path=/boot", "update"])
  File "/nix/store/5bh6rpya1ar6l49vrhx1rg58dsa42906-python3-3.9.6/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/q0881awy50g4srnnwasci37y2jk5sf99-systemd-249.5/bin/bootctl', '--path=/boot', 'update']' returned non-zero exit status 1.
warning: error(s) occurred while switching to the new configuration
make[1]: *** [vm/switch] Error 1
make: *** [vm/bootstrap] Error 2
```

Curious if you or others have seen this, and if there's a particular setting that could be triggering it.

**Comment by ihgann** [comment]
I did a little bit more research and I think I'm running into https://github.com/NixOS/nixpkgs/issues/152795. The line that caught my eye was:

```
updating systemd-boot from (249.7) to (249.5)
```

Based on the associated issue, this should be fixed in an upcoming update to NixOS. I pulled the NixOS `21.05` iso and ran the scripts (I had to remove `1password`) and it worked out of the box. This is a *huge* help at helping me both understand and dissect how NixOS works, and how to build my own dotfiles around it.
